language: r
sudo: required
cache: packages

r:
  - devel
  - release

os:
  - linux
  
env:
  - _R_CHECK_TESTS_NLINES_=0
  
script:
  - |
    R CMD build .
    travis_wait 180 R CMD check --no-build-vignettes --no-manual COVID19*tar.gz
  