on:
  
  push:
  
  schedule:
    
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'

name: pkgdown

jobs:
  
  pkgdown:
    
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    
      - name: Credentials
        run: |
            git config --global user.email "emanuele.guidotti@unine.ch"
            git config --global user.name "Emanuele Guidotti"
      
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      
      - name: Install FriBidi
        run: sudo apt-get install -y libfribidi-dev
      
      - name: Install HarfBuzz
        run: sudo apt-get install -y libharfbuzz-dev

      - name: Install dependencies
        run: |
          install.packages("DT")
          install.packages("remotes")
          install.packages("https://cran.r-project.org/src/contrib/Archive/pkgdown/pkgdown_1.6.1.tar.gz", repos=NULL, type="source")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE)
        shell: Rscript {0}
